version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: mounidocker/microservice-image
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true 
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t mounidocker/microservice-one:$TAG .      # (4)
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (5)
          docker push mounidocker/microservice-one:$TAG
          az login --service-principal --username "2953a566-55eb-4d9a-a776-ab763de46b50" --password "d6c46999-e42c-4990-b81e-a16b265a6482" --tenant "f14cc82e-80b6-4f74-b91d-7fafc039c0b5"
          az aks get-credentials --resource-group acctestRG1 --name acctestaks1
          kubectl apply -f microservice-deployment.yaml


        